import {
    Shirt,
    Watch,
    BookOpen,
    Headphones,
    Coffee,
    Backpack,
} from "lucide-react";

export const PRODUCTS = [
    {
        id: "oversized-hoodie",
        name: "Oversized Hoodie",
        description: "Thick fleece, dropped shoulders. Great for cold nights.",
        price: 890,
        stock: 10,
        badge: "Best Seller",
        icon: Shirt,
        color: "bg-stone-100",
        accent: "text-stone-500",
    },
    {
        id: "canvas-tote",
        name: "Canvas Tote Bag",
        description: "Heavy-duty canvas with interior pocket. Fits everything.",
        price: 350,
        stock: 20,
        badge: null,
        icon: Backpack,
        color: "bg-amber-50",
        accent: "text-amber-500",
    },
    {
        id: "wireless-earbuds",
        name: "Wireless Earbuds",
        description: "30hr battery, noise isolation, USB-C charging case.",
        price: 1499,
        stock: 8,
        badge: "New",
        icon: Headphones,
        color: "bg-blue-50",
        accent: "text-blue-400",
    },
    {
        id: "leather-watch",
        name: "Minimalist Watch",
        description: "Genuine leather strap, Japanese quartz movement.",
        price: 2200,
        stock: 5,
        badge: "Limited",
        icon: Watch,
        color: "bg-rose-50",
        accent: "text-rose-400",
    },
    {
        id: "notebook-a5",
        name: "Dotted Notebook A5",
        description:
            "180gsm paper, lay-flat binding. Perfect for bullet journaling.",
        price: 280,
        stock: 30,
        badge: null,
        icon: BookOpen,
        color: "bg-green-50",
        accent: "text-green-500",
    },
    {
        id: "ceramic-mug",
        name: "Ceramic Coffee Mug",
        description:
            "400ml hand-thrown ceramic. Microwave and dishwasher safe.",
        price: 420,
        stock: 15,
        badge: null,
        icon: Coffee,
        color: "bg-orange-50",
        accent: "text-orange-400",
    },
];
